### ISSUE TITLE
Exoscale ipv6 rule causes exception

### ISSUE THREAD

**Issue by philipgh1** [janoszen/cscanner#14]
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.security.InvalidParameterException: Invalid protocol name: icmpv6
        at com.opsbears.cscanner.firewall.Protocols.getProtocolIdByName(Protocols.java:166)
        at com.opsbears.cscanner.exoscale.ExoscaleFirewallClient.extractRules(ExoscaleFirewallClient.java:71)
        at com.opsbears.cscanner.exoscale.ExoscaleFirewallClient.listFirewallGroups(ExoscaleFirewallClient.java:56)
        at com.opsbears.cscanner.firewall.FirewallPublicServiceProhibitedRule.evaluate(FirewallPublicServiceProhibitedRule.java:33)
        at com.opsbears.cscanner.firewall.FirewallPublicServiceProhibitedRule.evaluate(FirewallPublicServiceProhibitedRule.java:12)
        at com.opsbears.cscanner.core.ScannerCore.scan(ScannerCore.java:89)
        at com.opsbears.cscanner.cli.CLIApplication.main(CLIApplication.java:27)
```

**Comment by janoszen** [comment]
Fixed, releasing in the 0.0.2 release.
