### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by philipgh1** [janoszen/cscanner#32]
java -jar cscanner.jar --list-ips fwpolicy.yaml
Exception in thread "main" java.lang.NullPointerException
        at com.opsbears.cscanner.exoscale.ExoscaleHostDiscoveryClient.listIpAddresses(ExoscaleHostDiscoveryClient.java:50)
        at com.opsbears.cscanner.core.ScannerCore.listIps(ScannerCore.java:89)
        at com.opsbears.cscanner.cli.CLIApplication.run(CLIApplication.java:132)
        at com.opsbears.cscanner.cli.CLIApplication.main(CLIApplication.java:189)

**Comment by philipgh1** [comment]
This organization might be empty, but I cannot verify it right now - will follow up.

**Comment by philipgh1** [comment]
Yes, the organization is empty.

**Comment by janoszen** [comment]
Understood, will fix.
